# stubs/OpenGL.pyi

from typing import Any

def glClearColor(red: float, green: float, blue: float, alpha: float) -> None: ...
def glEnable(cap: int) -> None: ...
def glViewport(x: int, y: int, width: int, height: int) -> None: ...
def glMatrixMode(mode: int) -> None: ...
def glLoadIdentity() -> None: ...
def gluPerspective(fovy: float, aspect: float, zNear: float, zFar: float) -> None: ...
