# stubs/PyQt5/QtCore.pyi

from typing import Any

class Qt:
    AlignCenter: Any = ...
    Key_F11: Any = ...
    LeftButton: Any = ...
    RightButton: Any = ...
    MiddleButton: Any = ...
    Key_Escape: Any = ...

class QThread:
    def __init__(self, parent: Any = None) -> None: ...
