# stubs/PyQt5/QtWidgets.pyi

from typing import Any

class QApplication:
    def __init__(self, argv: list[str]) -> None: ...
    def exec_(self) -> int: ...
    def quit(self) -> None: ...
    @staticmethod
    def primaryScreen() -> Any: ...

class QWidget:
    def __init__(self, parent: Any = None) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def setLayout(self, layout: Any) -> None: ...

class QPushButton(QWidget):
    def __init__(self, text: str, parent: Any = None) -> None: ...
    def clicked(self) -> Any: ...

class QMainWindow(QWidget):
    def __init__(self, parent: Any = None) -> None: ...
    def setCentralWidget(self, widget: Any) -> None: ...
    def menuBar(self) -> Any: ...
    def close(self) -> None: ...
    def setWindowIcon(self, icon: Any) -> None: ...
    def setGeometry(self, x: int, y: int, width: int, height: int) -> None: ...
    def setPalette(self, palette: Any) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def findChildren(self, type: Any) -> Any: ...
    def isFullScreen(self) -> bool: ...
    def showNormal(self) -> None: ...
    def showFullScreen(self) -> None: ...
    def centralWidget(self) -> Any: ...
    def show(self) -> None: ...

class QOpenGLWidget:
    def __init__(self, parent: Any = None) -> None: ...
    def initializeGL(self) -> None: ...
    def resizeGL(self, width: int, height: int) -> None: ...
    def paintGL(self) -> None: ...

class QMenu:
    def __init__(self, title: str = "", parent: Any = None) -> None: ...
    def addAction(self, *args: Any, **kwargs: Any) -> Any: ...

class QMenuBar:
    def __init__(self, parent: Any = None) -> None: ...
    def addMenu(self, menu: Any) -> Any: ...

class QAction:
    def __init__(self, text: str, parent: Any = None) -> None: ...
    def triggered(self) -> Any: ...

class QVBoxLayout:
    def __init__(self, parent: Any = None) -> None: ...
    def addWidget(self, widget: Any) -> None: ...
    def setAlignment(self, alignment: Any) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...

class QSystemTrayIcon:
    def __init__(self, icon: Any, parent: Any = None) -> None: ...
    def show(self) -> None: ...
    def setContextMenu(self, menu: Any) -> None: ...
